definitions:
  example.DataResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/example.Item'
        type: array
      status:
        example: success
        type: string
    type: object
  example.Item:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: Item A
        type: string
    type: object
info:
  contact: {}
paths:
  /User:
    get:
      consumes:
      - application/json
      description: Reads and sends the content of a static data.json file.
      produces:
      - application/json
      responses:
        "200":
          description: The data from the JSON file
          schema:
            $ref: '#/definitions/example.DataResponse'
        "500":
          description: Could not read data file.
          schema:
            type: string
      summary: Get static data
      tags:
      - example
swagger: "2.0"
